version: "3.5"

services:
  proxy:
    image: haproxy:latest
    restart: always
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
      - ./certs:/usr/local/etc/certs:ro
    ports:
      - 80:80
      - 443:443

  nginx-certbot:
    image: nginx
    restart: always
    container_name: nginx-certbot
    volumes:
      - ./webroot:/usr/share/nginx/html
